# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  server:
    container_name: server
    environment:
      DATABASE_URL: mongodb://brook:brook-mongo-2022@localhost:27017/library
    build:
      context: '.'
      target: base
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - test_vm
  db:
    image: mongo:5.0
    restart: always
    container_name: db
    ports:
      - '27017:27017'
    environment:
      MONGODB_USER: brook
      MONGODB_PASSWORD: brook-mongo-2022
      MONGODB_DB: library
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge
